[package]
name = "t_torrent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bendy = "^0.3"
ureq = "2.4.0"
sha1 = "^0.10"
threadpool = "^1.8"
dirs = "4.0.0"